-- ============================================================================
-- Phase 6A: Learning Tracker Schema Migration
-- ============================================================================
--
-- This migration introduces tables for tracking Knowledge Bot recommendations
-- and their learning outcomes. The Learning Tracker enables Knowledge Bots
-- to improve over time by tracking which recommendations succeed.
--
-- TABLES:
-- - monolith_recommendations: Individual recommendations from Knowledge Bots
-- - monolith_knowledge_bot_learning: Learning data per bot/subordinate/pattern
-- - monolith_knowledge_bot_metrics: Aggregate metrics per Knowledge Bot
-- - monolith_knowledge_bot_metrics_history: Historical metrics for trend analysis
--
-- Part of the Neural Stack architecture for the Monolith System.
-- ============================================================================

-- ============================================================================
-- 1. RECOMMENDATIONS TABLE
-- ============================================================================
-- Stores individual recommendations generated by Knowledge Bots

CREATE TABLE IF NOT EXISTS monolith_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Source identification
  knowledge_bot_role TEXT NOT NULL,        -- 'tech_kb', 'marketing_kb', etc.
  subordinate_role TEXT NOT NULL,          -- Target subordinate agent

  -- Recommendation content
  targeting_pattern TEXT NOT NULL,         -- Pattern being addressed (e.g., 'task_category:deployment')
  recommendation_text TEXT NOT NULL,       -- The actual recommendation

  -- Status tracking
  status TEXT DEFAULT 'generated' CHECK (status IN (
    'generated',    -- Just created
    'selected',     -- Selected by Team Lead
    'rejected',     -- Rejected by Team Lead
    'expired'       -- Not acted upon within time window
  )),

  -- Link to amendment (if selected)
  amendment_id UUID REFERENCES monolith_amendments(id),
  selected_at TIMESTAMPTZ,

  -- Outcome tracking (populated after amendment evaluation)
  outcome_succeeded BOOLEAN,
  outcome_impact NUMERIC(10,4),            -- variance_before - variance_after
  variance_before NUMERIC(10,4),
  variance_after NUMERIC(10,4),
  outcome_recorded_at TIMESTAMPTZ,

  -- Metadata
  expected_impact TEXT DEFAULT 'medium' CHECK (expected_impact IN ('high', 'medium', 'low')),
  research_depth INTEGER DEFAULT 1,        -- How many data sources consulted

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for recommendation queries
CREATE INDEX IF NOT EXISTS idx_recommendations_bot ON monolith_recommendations(knowledge_bot_role);
CREATE INDEX IF NOT EXISTS idx_recommendations_subordinate ON monolith_recommendations(subordinate_role);
CREATE INDEX IF NOT EXISTS idx_recommendations_pattern ON monolith_recommendations(targeting_pattern);
CREATE INDEX IF NOT EXISTS idx_recommendations_amendment ON monolith_recommendations(amendment_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_status ON monolith_recommendations(status);
CREATE INDEX IF NOT EXISTS idx_recommendations_created ON monolith_recommendations(created_at DESC);

-- Composite index for common query: find recommendations by bot and subordinate
CREATE INDEX IF NOT EXISTS idx_recommendations_bot_subordinate ON monolith_recommendations(knowledge_bot_role, subordinate_role);

-- ============================================================================
-- 2. KNOWLEDGE BOT LEARNING TABLE
-- ============================================================================
-- Stores learning data per Knowledge Bot + subordinate + pattern combination
-- This is the core learning state that adjusts recommendation priority

CREATE TABLE IF NOT EXISTS monolith_knowledge_bot_learning (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Identification (unique constraint on combination)
  knowledge_bot_role TEXT NOT NULL,
  subordinate_role TEXT NOT NULL,
  targeting_pattern TEXT NOT NULL,

  -- Learning metrics
  total_recommendations INTEGER DEFAULT 0,
  successful_recommendations INTEGER DEFAULT 0,
  failed_recommendations INTEGER DEFAULT 0,
  avg_impact NUMERIC(10,4) DEFAULT 0,       -- Running average of outcome impact

  -- Calculated confidence score (0-1)
  confidence_score NUMERIC(5,4) DEFAULT 0 CHECK (confidence_score >= 0 AND confidence_score <= 1),

  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(knowledge_bot_role, subordinate_role, targeting_pattern)
);

-- Indexes for learning queries
CREATE INDEX IF NOT EXISTS idx_learning_bot ON monolith_knowledge_bot_learning(knowledge_bot_role);
CREATE INDEX IF NOT EXISTS idx_learning_subordinate ON monolith_knowledge_bot_learning(subordinate_role);
CREATE INDEX IF NOT EXISTS idx_learning_pattern ON monolith_knowledge_bot_learning(targeting_pattern);
CREATE INDEX IF NOT EXISTS idx_learning_confidence ON monolith_knowledge_bot_learning(confidence_score DESC);

-- Composite index for priority adjustment lookups
CREATE INDEX IF NOT EXISTS idx_learning_bot_subordinate ON monolith_knowledge_bot_learning(knowledge_bot_role, subordinate_role);

-- ============================================================================
-- 3. KNOWLEDGE BOT METRICS TABLE
-- ============================================================================
-- Aggregate metrics per Knowledge Bot for dashboard display

CREATE TABLE IF NOT EXISTS monolith_knowledge_bot_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  role TEXT UNIQUE NOT NULL,                -- 'tech_kb', 'marketing_kb', etc.

  -- Recommendation counts
  total_recommendations_generated INTEGER DEFAULT 0,
  recommendations_selected INTEGER DEFAULT 0,
  recommendations_succeeded INTEGER DEFAULT 0,
  recommendations_failed INTEGER DEFAULT 0,

  -- Performance metrics
  avg_research_depth NUMERIC(5,2) DEFAULT 1,

  -- Timestamps
  last_recommendation_at TIMESTAMPTZ,
  last_outcome_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for role lookup
CREATE INDEX IF NOT EXISTS idx_bot_metrics_role ON monolith_knowledge_bot_metrics(role);

-- ============================================================================
-- 4. KNOWLEDGE BOT METRICS HISTORY TABLE
-- ============================================================================
-- Historical snapshots for trend calculation

CREATE TABLE IF NOT EXISTS monolith_knowledge_bot_metrics_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  role TEXT NOT NULL,

  -- Snapshot metrics
  success_rate NUMERIC(5,4),
  selection_rate NUMERIC(5,4),
  total_recommendations INTEGER,
  successful_recommendations INTEGER,

  recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for history queries
CREATE INDEX IF NOT EXISTS idx_bot_metrics_history_role ON monolith_knowledge_bot_metrics_history(role);
CREATE INDEX IF NOT EXISTS idx_bot_metrics_history_recorded ON monolith_knowledge_bot_metrics_history(recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_bot_metrics_history_role_recorded ON monolith_knowledge_bot_metrics_history(role, recorded_at DESC);

-- ============================================================================
-- 5. SEED DATA: 6 KNOWLEDGE BOTS
-- ============================================================================

INSERT INTO monolith_knowledge_bot_metrics (role) VALUES
  ('tech_kb'),
  ('marketing_kb'),
  ('product_kb'),
  ('operations_kb'),
  ('finance_kb'),
  ('people_kb')
ON CONFLICT (role) DO NOTHING;

-- ============================================================================
-- 6. HELPER FUNCTIONS
-- ============================================================================

-- Function to increment recommendations_generated atomically
CREATE OR REPLACE FUNCTION increment_recommendations_generated(bot_role TEXT)
RETURNS VOID AS $$
BEGIN
  UPDATE monolith_knowledge_bot_metrics
  SET total_recommendations_generated = total_recommendations_generated + 1,
      last_recommendation_at = NOW(),
      updated_at = NOW()
  WHERE role = bot_role;

  -- Insert if not exists
  IF NOT FOUND THEN
    INSERT INTO monolith_knowledge_bot_metrics (role, total_recommendations_generated, last_recommendation_at)
    VALUES (bot_role, 1, NOW())
    ON CONFLICT (role) DO UPDATE SET
      total_recommendations_generated = monolith_knowledge_bot_metrics.total_recommendations_generated + 1,
      last_recommendation_at = NOW(),
      updated_at = NOW();
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to snapshot metrics for history (call daily/weekly)
CREATE OR REPLACE FUNCTION snapshot_knowledge_bot_metrics()
RETURNS VOID AS $$
BEGIN
  INSERT INTO monolith_knowledge_bot_metrics_history (role, success_rate, selection_rate, total_recommendations, successful_recommendations)
  SELECT
    role,
    CASE WHEN (recommendations_succeeded + recommendations_failed) > 0
         THEN recommendations_succeeded::NUMERIC / (recommendations_succeeded + recommendations_failed)
         ELSE 0 END AS success_rate,
    CASE WHEN total_recommendations_generated > 0
         THEN recommendations_selected::NUMERIC / total_recommendations_generated
         ELSE 0 END AS selection_rate,
    total_recommendations_generated,
    recommendations_succeeded
  FROM monolith_knowledge_bot_metrics;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 7. TRIGGERS
-- ============================================================================

-- Trigger to update timestamps
CREATE OR REPLACE FUNCTION update_learning_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.last_updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_learning_updated_at ON monolith_knowledge_bot_learning;
CREATE TRIGGER trigger_learning_updated_at
  BEFORE UPDATE ON monolith_knowledge_bot_learning
  FOR EACH ROW
  EXECUTE FUNCTION update_learning_updated_at();

DROP TRIGGER IF EXISTS trigger_recommendations_updated_at ON monolith_recommendations;
CREATE TRIGGER trigger_recommendations_updated_at
  BEFORE UPDATE ON monolith_recommendations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trigger_bot_metrics_updated_at ON monolith_knowledge_bot_metrics;
CREATE TRIGGER trigger_bot_metrics_updated_at
  BEFORE UPDATE ON monolith_knowledge_bot_metrics
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- 8. VIEWS
-- ============================================================================

-- View: Knowledge Bot performance summary
CREATE OR REPLACE VIEW monolith_knowledge_bot_summary AS
SELECT
  m.role,
  m.total_recommendations_generated,
  m.recommendations_selected,
  m.recommendations_succeeded,
  m.recommendations_failed,
  CASE WHEN m.total_recommendations_generated > 0
       THEN ROUND(m.recommendations_selected::NUMERIC / m.total_recommendations_generated * 100, 1)
       ELSE 0 END AS selection_rate_pct,
  CASE WHEN (m.recommendations_succeeded + m.recommendations_failed) > 0
       THEN ROUND(m.recommendations_succeeded::NUMERIC / (m.recommendations_succeeded + m.recommendations_failed) * 100, 1)
       ELSE 0 END AS success_rate_pct,
  m.avg_research_depth,
  m.last_recommendation_at,
  m.last_outcome_at
FROM monolith_knowledge_bot_metrics m;

-- View: Learning data with success rates
CREATE OR REPLACE VIEW monolith_learning_summary AS
SELECT
  l.knowledge_bot_role,
  l.subordinate_role,
  l.targeting_pattern,
  l.total_recommendations,
  l.successful_recommendations,
  l.failed_recommendations,
  CASE WHEN l.total_recommendations > 0
       THEN ROUND(l.successful_recommendations::NUMERIC / l.total_recommendations * 100, 1)
       ELSE 0 END AS success_rate_pct,
  ROUND(l.avg_impact::NUMERIC, 4) AS avg_impact,
  ROUND(l.confidence_score::NUMERIC, 4) AS confidence_score,
  l.last_updated_at
FROM monolith_knowledge_bot_learning l
ORDER BY l.knowledge_bot_role, l.confidence_score DESC;

-- View: Cross-subordinate insights
CREATE OR REPLACE VIEW monolith_cross_subordinate_insights AS
SELECT
  l.knowledge_bot_role,
  l.targeting_pattern,
  COUNT(DISTINCT l.subordinate_role) AS subordinates_helped,
  SUM(l.successful_recommendations) AS total_successes,
  ROUND(AVG(l.avg_impact)::NUMERIC, 4) AS avg_impact,
  ROUND(AVG(l.confidence_score)::NUMERIC, 4) AS avg_confidence
FROM monolith_knowledge_bot_learning l
WHERE l.successful_recommendations > 0
GROUP BY l.knowledge_bot_role, l.targeting_pattern
HAVING COUNT(DISTINCT l.subordinate_role) > 1
ORDER BY subordinates_helped DESC, total_successes DESC;

-- ============================================================================
-- 9. ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE monolith_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE monolith_knowledge_bot_learning ENABLE ROW LEVEL SECURITY;
ALTER TABLE monolith_knowledge_bot_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE monolith_knowledge_bot_metrics_history ENABLE ROW LEVEL SECURITY;

-- Permissive policies (adjust for production)
CREATE POLICY "Allow all for recommendations" ON monolith_recommendations FOR ALL USING (true);
CREATE POLICY "Allow all for learning" ON monolith_knowledge_bot_learning FOR ALL USING (true);
CREATE POLICY "Allow all for bot_metrics" ON monolith_knowledge_bot_metrics FOR ALL USING (true);
CREATE POLICY "Allow all for bot_metrics_history" ON monolith_knowledge_bot_metrics_history FOR ALL USING (true);

-- Grant permissions
GRANT ALL ON monolith_recommendations TO anon, authenticated;
GRANT ALL ON monolith_knowledge_bot_learning TO anon, authenticated;
GRANT ALL ON monolith_knowledge_bot_metrics TO anon, authenticated;
GRANT ALL ON monolith_knowledge_bot_metrics_history TO anon, authenticated;
GRANT SELECT ON monolith_knowledge_bot_summary TO anon, authenticated;
GRANT SELECT ON monolith_learning_summary TO anon, authenticated;
GRANT SELECT ON monolith_cross_subordinate_insights TO anon, authenticated;

-- ============================================================================
-- 10. COMMENTS
-- ============================================================================

COMMENT ON TABLE monolith_recommendations IS 'Individual recommendations generated by Knowledge Bots for subordinate improvement';
COMMENT ON TABLE monolith_knowledge_bot_learning IS 'Learning data tracking recommendation success per bot/subordinate/pattern combination';
COMMENT ON TABLE monolith_knowledge_bot_metrics IS 'Aggregate performance metrics per Knowledge Bot';
COMMENT ON TABLE monolith_knowledge_bot_metrics_history IS 'Historical metrics snapshots for trend calculation';

COMMENT ON FUNCTION increment_recommendations_generated IS 'Atomically increment recommendation count for a Knowledge Bot';
COMMENT ON FUNCTION snapshot_knowledge_bot_metrics IS 'Create historical snapshot of all Knowledge Bot metrics (call daily/weekly)';

COMMENT ON VIEW monolith_knowledge_bot_summary IS 'Dashboard summary of Knowledge Bot performance';
COMMENT ON VIEW monolith_learning_summary IS 'Learning data with calculated success rates';
COMMENT ON VIEW monolith_cross_subordinate_insights IS 'Patterns that have helped multiple subordinates';

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
