-- ============================================================================
-- Phase 6B: Knowledge Bot Schema Migration
-- ============================================================================
--
-- This migration establishes the database infrastructure for the Knowledge Bot
-- system - the second layer of the Neural Stack hierarchy.
--
-- Knowledge Bots are specialized agents that:
--   1. Continuously research industry trends, best practices, and new techniques
--   2. Observe subordinate agent performance patterns and failure modes
--   3. Generate targeted knowledge recommendations to improve agent capabilities
--   4. Learn from recommendation outcomes to improve future suggestions
--
-- Hierarchy: CEO -> Team Leads -> Knowledge Bots -> Individual Contributors
--
-- Each team has one Knowledge Bot:
--   - tech_knowledge_bot (Tech Team, reports to CTO)
--   - marketing_knowledge_bot (Marketing Team, reports to CMO)
--   - product_knowledge_bot (Product Team, reports to CPO)
--   - ops_knowledge_bot (Operations Team, reports to COO)
--   - finance_knowledge_bot (Finance Team, reports to CFO)
--   - people_knowledge_bot (People Team, reports to CHRO)
--
-- ============================================================================

-- ============================================================================
-- Table 1: monolith_knowledge_recommendations
-- ============================================================================
-- Stores recommendations generated by Knowledge Bots for their subordinates.
-- Tracks the full lifecycle from generation through application and outcome.

CREATE TABLE IF NOT EXISTS monolith_knowledge_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Source identification
  knowledge_bot_role TEXT NOT NULL,           -- Which Knowledge Bot generated this
  subordinate_role TEXT NOT NULL,             -- Target agent for this recommendation
  recommendation_date DATE NOT NULL,          -- When recommendation was generated

  -- Recommendation content
  recommendation_type TEXT NOT NULL,          -- 'knowledge_addition', 'knowledge_modification', 'skill_suggestion'
  recommendation_content TEXT NOT NULL,       -- The actual recommendation text/instructions
  expected_impact TEXT,                       -- 'high', 'medium', 'low' - predicted improvement
  research_sources JSONB,                     -- URLs, papers, docs that informed this recommendation
  targeting_pattern TEXT,                     -- What failure pattern this recommendation addresses

  -- Status tracking
  status TEXT DEFAULT 'pending',              -- 'pending', 'selected', 'applied', 'succeeded', 'failed', 'expired'
  selected_at TIMESTAMPTZ,                    -- When Team Lead selected this recommendation
  applied_at TIMESTAMPTZ,                     -- When amendment was created from this

  -- Outcome tracking (for Knowledge Bot learning feedback loop)
  amendment_id UUID REFERENCES monolith_amendments(id),  -- Link to resulting amendment
  outcome_variance_before NUMERIC,            -- Agent's variance score before amendment
  outcome_variance_after NUMERIC,             -- Agent's variance score after amendment
  outcome_success BOOLEAN,                    -- Did the recommendation improve performance?
  outcome_notes TEXT,                         -- Additional context about outcome

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ                      -- Recommendations expire after 7 days if not used
);

-- Add constraint for valid recommendation types
ALTER TABLE monolith_knowledge_recommendations
  ADD CONSTRAINT chk_recommendation_type
  CHECK (recommendation_type IN ('knowledge_addition', 'knowledge_modification', 'skill_suggestion'));

-- Add constraint for valid status values
ALTER TABLE monolith_knowledge_recommendations
  ADD CONSTRAINT chk_recommendation_status
  CHECK (status IN ('pending', 'selected', 'applied', 'succeeded', 'failed', 'expired'));

-- Add constraint for valid expected impact values
ALTER TABLE monolith_knowledge_recommendations
  ADD CONSTRAINT chk_expected_impact
  CHECK (expected_impact IS NULL OR expected_impact IN ('high', 'medium', 'low'));

COMMENT ON TABLE monolith_knowledge_recommendations IS
  'Stores recommendations generated by Knowledge Bots to improve subordinate agent performance';


-- ============================================================================
-- Table 2: monolith_knowledge_bot_learning
-- ============================================================================
-- Tracks Knowledge Bot learning from recommendation outcomes.
-- Aggregates success/failure patterns to improve future recommendation quality.

CREATE TABLE IF NOT EXISTS monolith_knowledge_bot_learning (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Bot and target identification
  knowledge_bot_role TEXT NOT NULL,           -- Which Knowledge Bot this learning belongs to
  subordinate_role TEXT NOT NULL,             -- Which subordinate agent this is about

  -- Pattern identification
  targeting_pattern TEXT NOT NULL,            -- The failure pattern being addressed
  recommendation_type TEXT NOT NULL,          -- Type of recommendations made for this pattern

  -- Outcome statistics
  total_recommendations INTEGER DEFAULT 0,    -- Total recommendations made for this pattern
  successful_recommendations INTEGER DEFAULT 0,  -- How many succeeded
  failed_recommendations INTEGER DEFAULT 0,   -- How many failed
  avg_impact NUMERIC,                         -- Average variance improvement achieved

  -- Learning adjustments
  confidence_score NUMERIC DEFAULT 0.5,       -- 0-1 scale, increases with consistent success
  last_success_date DATE,                     -- Most recent successful recommendation
  last_failure_date DATE,                     -- Most recent failed recommendation

  -- Timestamp
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add constraint for valid confidence score range
ALTER TABLE monolith_knowledge_bot_learning
  ADD CONSTRAINT chk_confidence_score
  CHECK (confidence_score >= 0 AND confidence_score <= 1);

COMMENT ON TABLE monolith_knowledge_bot_learning IS
  'Tracks Knowledge Bot learning from recommendation outcomes to improve future suggestions';


-- ============================================================================
-- Table 3: monolith_knowledge_bots
-- ============================================================================
-- Configuration and state storage for each Knowledge Bot agent.

CREATE TABLE IF NOT EXISTS monolith_knowledge_bots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Identity
  role TEXT UNIQUE NOT NULL,                  -- e.g., 'tech_knowledge_bot'
  team_id TEXT NOT NULL REFERENCES monolith_teams(team_id),  -- Which team this bot serves
  reports_to TEXT NOT NULL,                   -- Team Lead role this bot reports to

  -- Configuration
  research_focus JSONB,                       -- Array of focus areas for research
  subordinate_specialties JSONB,              -- Map of subordinate role -> specialty areas

  -- Activity tracking
  last_research_cycle TIMESTAMPTZ,            -- When last research cycle completed
  recommendations_generated INTEGER DEFAULT 0,  -- Total recommendations ever generated
  recommendations_succeeded INTEGER DEFAULT 0,  -- Total successful recommendations

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE monolith_knowledge_bots IS
  'Configuration and state for Knowledge Bot agents in the Neural Stack hierarchy';


-- ============================================================================
-- Indexes
-- ============================================================================

-- Recommendations indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_recommendations_subordinate
  ON monolith_knowledge_recommendations(subordinate_role);

CREATE INDEX IF NOT EXISTS idx_recommendations_status
  ON monolith_knowledge_recommendations(status);

CREATE INDEX IF NOT EXISTS idx_recommendations_date
  ON monolith_knowledge_recommendations(recommendation_date);

CREATE INDEX IF NOT EXISTS idx_recommendations_knowledge_bot
  ON monolith_knowledge_recommendations(knowledge_bot_role);

-- Composite index for finding pending recommendations for a specific bot's subordinates
CREATE INDEX IF NOT EXISTS idx_recommendations_bot_status
  ON monolith_knowledge_recommendations(knowledge_bot_role, status, recommendation_date);

-- Knowledge Bot Learning unique constraint and index
-- Each bot should have one learning record per (subordinate, pattern, type) combination
CREATE UNIQUE INDEX IF NOT EXISTS idx_kb_learning_unique
  ON monolith_knowledge_bot_learning(knowledge_bot_role, subordinate_role, targeting_pattern, recommendation_type);

-- Knowledge Bots team lookup
CREATE INDEX IF NOT EXISTS idx_knowledge_bots_team
  ON monolith_knowledge_bots(team_id);


-- ============================================================================
-- Seed Data: Initialize the 6 Knowledge Bots
-- ============================================================================

INSERT INTO monolith_knowledge_bots (role, team_id, reports_to, research_focus, subordinate_specialties)
VALUES
  -- Tech Knowledge Bot
  (
    'tech_knowledge_bot',
    'tech',
    'cto',
    '["software architecture", "emerging technologies", "development best practices", "security patterns", "performance optimization", "AI/ML advances"]'::JSONB,
    '{
      "software_engineer": ["coding patterns", "frameworks", "testing", "code quality"],
      "devops_engineer": ["infrastructure", "CI/CD", "monitoring", "cloud platforms"],
      "security_analyst": ["security tools", "threat patterns", "compliance", "penetration testing"]
    }'::JSONB
  ),

  -- Marketing Knowledge Bot
  (
    'marketing_knowledge_bot',
    'marketing',
    'cmo',
    '["digital marketing trends", "content strategy", "brand development", "marketing analytics", "social media algorithms", "SEO/SEM advances"]'::JSONB,
    '{
      "content_strategist": ["content formats", "storytelling", "SEO", "engagement metrics"],
      "brand_manager": ["brand positioning", "visual identity", "brand voice", "reputation management"],
      "growth_marketer": ["acquisition channels", "conversion optimization", "A/B testing", "funnel analysis"]
    }'::JSONB
  ),

  -- Product Knowledge Bot
  (
    'product_knowledge_bot',
    'product',
    'cpo',
    '["product management methodologies", "user research techniques", "roadmap planning", "competitive analysis", "feature prioritization", "product analytics"]'::JSONB,
    '{
      "product_manager": ["roadmapping", "stakeholder management", "metrics", "prioritization frameworks"],
      "ux_designer": ["design systems", "user testing", "accessibility", "interaction patterns"],
      "product_analyst": ["analytics tools", "data visualization", "cohort analysis", "experimentation"]
    }'::JSONB
  ),

  -- Operations Knowledge Bot
  (
    'ops_knowledge_bot',
    'operations',
    'coo',
    '["operational excellence", "process optimization", "supply chain management", "quality assurance", "lean methodologies", "automation tools"]'::JSONB,
    '{
      "operations_manager": ["process design", "resource allocation", "vendor management", "KPI tracking"],
      "quality_assurance": ["testing methodologies", "quality metrics", "compliance", "continuous improvement"],
      "project_coordinator": ["project management tools", "timeline optimization", "risk management", "stakeholder communication"]
    }'::JSONB
  ),

  -- Finance Knowledge Bot
  (
    'finance_knowledge_bot',
    'finance',
    'cfo',
    '["financial planning", "budgeting techniques", "financial modeling", "compliance updates", "investment strategies", "cost optimization"]'::JSONB,
    '{
      "financial_analyst": ["financial modeling", "forecasting", "valuation", "market analysis"],
      "accountant": ["accounting standards", "tax regulations", "audit preparation", "reporting tools"],
      "budget_manager": ["budget planning", "variance analysis", "cost control", "financial dashboards"]
    }'::JSONB
  ),

  -- People Knowledge Bot
  (
    'people_knowledge_bot',
    'people',
    'chro',
    '["talent management", "employee engagement", "organizational development", "HR technology", "diversity and inclusion", "workplace trends"]'::JSONB,
    '{
      "recruiter": ["sourcing strategies", "interview techniques", "employer branding", "ATS optimization"],
      "hr_specialist": ["employee relations", "policy development", "benefits administration", "compliance"],
      "learning_development": ["training design", "skill assessment", "career pathing", "mentorship programs"]
    }'::JSONB
  )
ON CONFLICT (role) DO UPDATE SET
  team_id = EXCLUDED.team_id,
  reports_to = EXCLUDED.reports_to,
  research_focus = EXCLUDED.research_focus,
  subordinate_specialties = EXCLUDED.subordinate_specialties,
  updated_at = NOW();


-- ============================================================================
-- Helper Functions
-- ============================================================================

-- Function to expire old pending recommendations
CREATE OR REPLACE FUNCTION expire_old_recommendations()
RETURNS INTEGER AS $$
DECLARE
  expired_count INTEGER;
BEGIN
  UPDATE monolith_knowledge_recommendations
  SET status = 'expired'
  WHERE status = 'pending'
    AND expires_at IS NOT NULL
    AND expires_at < NOW();

  GET DIAGNOSTICS expired_count = ROW_COUNT;
  RETURN expired_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION expire_old_recommendations() IS
  'Marks pending recommendations as expired if past their expiration date';


-- Function to update Knowledge Bot learning from recommendation outcome
CREATE OR REPLACE FUNCTION update_kb_learning_from_outcome(
  p_recommendation_id UUID,
  p_success BOOLEAN,
  p_variance_improvement NUMERIC
)
RETURNS VOID AS $$
DECLARE
  v_kb_role TEXT;
  v_sub_role TEXT;
  v_pattern TEXT;
  v_rec_type TEXT;
BEGIN
  -- Get recommendation details
  SELECT knowledge_bot_role, subordinate_role, targeting_pattern, recommendation_type
  INTO v_kb_role, v_sub_role, v_pattern, v_rec_type
  FROM monolith_knowledge_recommendations
  WHERE id = p_recommendation_id;

  IF v_kb_role IS NULL THEN
    RAISE EXCEPTION 'Recommendation not found: %', p_recommendation_id;
  END IF;

  -- Upsert learning record
  INSERT INTO monolith_knowledge_bot_learning (
    knowledge_bot_role,
    subordinate_role,
    targeting_pattern,
    recommendation_type,
    total_recommendations,
    successful_recommendations,
    failed_recommendations,
    avg_impact,
    confidence_score,
    last_success_date,
    last_failure_date,
    updated_at
  )
  VALUES (
    v_kb_role,
    v_sub_role,
    v_pattern,
    v_rec_type,
    1,
    CASE WHEN p_success THEN 1 ELSE 0 END,
    CASE WHEN p_success THEN 0 ELSE 1 END,
    p_variance_improvement,
    CASE WHEN p_success THEN 0.6 ELSE 0.4 END,
    CASE WHEN p_success THEN CURRENT_DATE ELSE NULL END,
    CASE WHEN NOT p_success THEN CURRENT_DATE ELSE NULL END,
    NOW()
  )
  ON CONFLICT (knowledge_bot_role, subordinate_role, targeting_pattern, recommendation_type)
  DO UPDATE SET
    total_recommendations = monolith_knowledge_bot_learning.total_recommendations + 1,
    successful_recommendations = monolith_knowledge_bot_learning.successful_recommendations +
      CASE WHEN p_success THEN 1 ELSE 0 END,
    failed_recommendations = monolith_knowledge_bot_learning.failed_recommendations +
      CASE WHEN p_success THEN 0 ELSE 1 END,
    avg_impact = (
      COALESCE(monolith_knowledge_bot_learning.avg_impact, 0) * monolith_knowledge_bot_learning.total_recommendations
      + COALESCE(p_variance_improvement, 0)
    ) / (monolith_knowledge_bot_learning.total_recommendations + 1),
    confidence_score = LEAST(1.0, GREATEST(0.0,
      monolith_knowledge_bot_learning.confidence_score +
      CASE WHEN p_success THEN 0.05 ELSE -0.05 END
    )),
    last_success_date = CASE WHEN p_success THEN CURRENT_DATE
      ELSE monolith_knowledge_bot_learning.last_success_date END,
    last_failure_date = CASE WHEN NOT p_success THEN CURRENT_DATE
      ELSE monolith_knowledge_bot_learning.last_failure_date END,
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION update_kb_learning_from_outcome(UUID, BOOLEAN, NUMERIC) IS
  'Updates Knowledge Bot learning records based on recommendation outcome';


-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Phase 6B Knowledge Bot schema is now ready.
--
-- Next steps:
--   1. Implement KnowledgeBot class in agents/roles/
--   2. Add Knowledge Bot to team hierarchy
--   3. Implement recommendation generation logic
--   4. Create Team Lead recommendation selection interface
--   5. Wire up outcome tracking for learning feedback loop
-- ============================================================================
