-- ============================================================================
-- KNOWLEDGE BOT RECOMMENDATIONS & RESEARCH LOG - Phase 6B Migration
-- Cognalith Inc. | Monolith System
--
-- This migration creates the data foundation for Knowledge Bot recommendations
-- and research cycle tracking as defined in Phase 6B.
-- ============================================================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- KNOWLEDGE BOT RECOMMENDATIONS TABLE
-- Stores recommendations generated by Knowledge Bots for subordinates
-- ============================================================================
CREATE TABLE IF NOT EXISTS monolith_kb_recommendations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Target identification
    subordinate_role TEXT NOT NULL,  -- The role receiving the recommendation
    knowledge_bot_role TEXT NOT NULL,  -- The KB that generated this recommendation

    -- Recommendation details
    type TEXT NOT NULL,  -- 'prompt_enhancement', 'knowledge_addition', 'workflow_optimization', etc.
    content JSONB NOT NULL,  -- The actual recommendation content
    expected_impact TEXT,  -- Description of expected improvement
    confidence NUMERIC(5,4) DEFAULT 0.8,  -- Confidence score 0-1

    -- Status tracking
    status TEXT DEFAULT 'pending',  -- 'pending', 'applied', 'dismissed', 'expired'

    -- Research context
    research_source TEXT,  -- Source of research that generated this
    research_context JSONB,  -- Additional context from research

    -- Amendment linkage
    applied_at TIMESTAMPTZ,  -- When recommendation was applied
    amendment_id UUID,  -- Links to monolith_amendments if applied

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Foreign key to amendments (if applied)
    CONSTRAINT fk_recommendation_amendment
        FOREIGN KEY (amendment_id)
        REFERENCES monolith_amendments(id)
        ON DELETE SET NULL
);

-- Indexes for recommendation queries
CREATE INDEX IF NOT EXISTS idx_kb_recommendations_subordinate ON monolith_kb_recommendations(subordinate_role);
CREATE INDEX IF NOT EXISTS idx_kb_recommendations_kb ON monolith_kb_recommendations(knowledge_bot_role);
CREATE INDEX IF NOT EXISTS idx_kb_recommendations_status ON monolith_kb_recommendations(status);
CREATE INDEX IF NOT EXISTS idx_kb_recommendations_type ON monolith_kb_recommendations(type);
CREATE INDEX IF NOT EXISTS idx_kb_recommendations_created ON monolith_kb_recommendations(created_at);
CREATE INDEX IF NOT EXISTS idx_kb_recommendations_pending ON monolith_kb_recommendations(status) WHERE status = 'pending';

-- ============================================================================
-- KNOWLEDGE BOT RESEARCH LOG TABLE
-- Records research cycles performed by Knowledge Bots
-- ============================================================================
CREATE TABLE IF NOT EXISTS monolith_kb_research_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Knowledge Bot identification
    knowledge_bot_role TEXT NOT NULL,  -- The KB that performed research

    -- Research details
    research_focus TEXT NOT NULL,  -- Topic/area of research
    sources_consulted JSONB DEFAULT '[]'::jsonb,  -- Array of sources consulted
    insights_found INTEGER DEFAULT 0,  -- Number of insights discovered
    recommendations_generated INTEGER DEFAULT 0,  -- Number of recommendations created

    -- Performance metrics
    duration_seconds INTEGER,  -- Time taken for research cycle

    completed_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for research log queries
CREATE INDEX IF NOT EXISTS idx_kb_research_log_kb ON monolith_kb_research_log(knowledge_bot_role);
CREATE INDEX IF NOT EXISTS idx_kb_research_log_completed ON monolith_kb_research_log(completed_at);
CREATE INDEX IF NOT EXISTS idx_kb_research_log_focus ON monolith_kb_research_log(research_focus);

-- ============================================================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================================================
ALTER TABLE monolith_kb_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE monolith_kb_research_log ENABLE ROW LEVEL SECURITY;

-- Create permissive policies for anon access (adjust for production)
CREATE POLICY "Allow all for kb_recommendations" ON monolith_kb_recommendations FOR ALL USING (true);
CREATE POLICY "Allow all for kb_research_log" ON monolith_kb_research_log FOR ALL USING (true);

-- Grant permissions
GRANT ALL ON monolith_kb_recommendations TO anon, authenticated;
GRANT ALL ON monolith_kb_research_log TO anon, authenticated;

-- ============================================================================
-- UPDATE TRIGGER FOR TIMESTAMPS
-- ============================================================================
DROP TRIGGER IF EXISTS trigger_update_kb_recommendations ON monolith_kb_recommendations;
CREATE TRIGGER trigger_update_kb_recommendations
    BEFORE UPDATE ON monolith_kb_recommendations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================
COMMENT ON TABLE monolith_kb_recommendations IS 'Recommendations generated by Knowledge Bots for team subordinates.';
COMMENT ON TABLE monolith_kb_research_log IS 'History of research cycles performed by Knowledge Bots.';
